spring:
    hadoop:
        fsUri: hdfs://10.211.55.3:9000
        resourceManagerHost: 10.211.55.3
    yarn:
        appName: mammoth-yarn
        applicationDir: /app/mammoth-yarn/
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: mammoth-yarn-container-1.0-SNAPSHOT.jar
